gejala = {
    "Ge01": "Muncul papul",
    "Ge02": "Muncul pustule",
    "Ge03": "Muncul nodul",
    "Ge04": "Muncul scar acne",
    "Ge05": "Area wajah, dada, punggung",
    "Ge06": "Usia remaja",
    "Ge07": "Kulit perih dan terbakar",
    "Ge08": "Kemerahan permanen",
    "Ge09": "Kulit kasar/membengkak",
    "Ge10": "Masalah pada mata",
    "Ge11": "Sentral wajah",
    "Ge12": "Usia 30–40 tahun",
    "Ge13": "Bintil kecil sekitar mulut",
    "Ge14": "Kulit merah dan bersisik",
    "Ge15": "Area mulut, hidung, mata",
    "Ge16": "Wanita muda",
    "Ge17": "Gatal",
    "Ge18": "Kemerahan ke alis & glabella",
    "Ge19": "Benjolan bernanah di folikel",
    "Ge20": "Punggung, bahu, dada atas",
    "Ge21": "Usia 13–45 tahun",
    "Ge22": "Kulit kasar & tidak rata",
    "Ge23": "Lengan, paha, pipi, bokong",
    "Ge24": "Anak-anak & remaja",
    "Ge25": "Benjolan besar bernanah",
    "Ge26": "Laki-laki dewasa",
    "Ge27": "Radang wajah & leher",
    "Ge28": "Semua umur"
}
